# Generated by Django 5.0.7 on 2024-10-05 13:29

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media_files', validators=[petstagram.photos.validators.FileSizeValidator(5.0)]),
        ),
    ]
