# Generated by Django 5.0.7 on 2024-10-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedPhoto',
            new_name='Like',
        ),
    ]
